SELECT client.NAME, PROJECT_COUNT FROM
  (SELECT CLIENT_ID, COUNT(CLIENT_ID) AS PROJECT_COUNT
   FROM PROJECT GROUP BY CLIENT_ID)
INNER JOIN client ON CLIENT_ID = client.ID
WHERE PROJECT_COUNT = (SELECT MAX(PROJECT_COUNT) FROM (SELECT CLIENT_ID, COUNT(CLIENT_ID) AS PROJECT_COUNT
                                                       FROM PROJECT GROUP BY CLIENT_ID));

